- name: Stop and remove old container
  shell: |
    docker stop {{ container_name }} || true
    docker rm {{ container_name }} || true

- name: Run new container on original port
  shell: docker run --pull=never -d --name {{ container_name }} -p {{ orig_port }}:5000 {{ image_name }}:{{ image_tag }}

- name: Update Nginx to point back to original port
  copy:
    dest: "{{ nginx_upstream_file }}"
    content: |
      upstream flask_backend {
          server localhost:{{ orig_port }};
      }

      server {
          listen 80;
          location / {
              proxy_pass http://flask_backend;
          }
      }
  notify: reload nginx
