- name: Zero downtime upgrade for flask-app with base image patch detection
  hosts: docker_hosts
  become: true
  vars:
    container_name: flask-app
    image_name: flask-app
    image_tag: "v{{ lookup('pipe', 'date +%y%m%d%H%M') }}"
    dockerfile_path: /home/ubuntu/flask-app/Dockerfile
    app_dir: /home/ubuntu/flask-app
    orig_port: 5000
    temp_port: 5001
    nginx_upstream_file: /etc/nginx/conf.d/upstream.conf
    tag_file: /home/ubuntu/last_deployed_image.txt
  roles:
    - build_image # 1. Build image
    - detect_vuln # 2. Check current container for vuln and image diff
    - run_container # 3. Run container on temp port
    - nginx_temp_switch # 4. Point nginx to temp and drain
    - nginx_switch_to_new # 5. Remove old, start new, repoint nginx
    - finalize_deployment # 6. Save tag, clean up

  handlers:
    - import_tasks: handlers/main.yml
