- name: Zero downtime upgrade for flask-app with base image patch detection
  hosts: docker_hosts
  become: true
  vars:
    container_name: flask-app
    image_name: flask-app
    dockerfile_path: /home/ubuntu/flask-app/Dockerfile
    app_dir: /home/ubuntu/flask-app
    orig_port: 5000
    temp_port: 5001
    nginx_upstream_file: /etc/nginx/conf.d/upstream.conf
    tag_file: /home/ubuntu/last_deployed_image.txt
    rollback_tag_file: /home/ubuntu/last_deployed_image.txt.previous

  roles:
    - build_image
    - detect_vuln
    - run_container
    - nginx_temp_switch
    - nginx_switch_to_new
    - finalize_deployment

  handlers:
    - import_tasks: handlers/main.yml
